### PR TITLE
Changed relative to absolute url to correct link.

### PR DESCRIPTION
**Pull request by mssgill**
Tested this locally and works fine.

### CODE REVIEW

**Comment by jonathansick** [comment]
Nice find 🕵 Seems like I missed this on all the install pages (I was copy-and-pasting across  all install type pages, as well as index.rst). Would you mind putting those fixes in this PR too? Thanks.

**Comment by mssgill** [comment]
Yep, cool, i'll fix all those later too!

**Comment by mssgill** [comment]
@jonathansick - Ok, i think i've fixed the url in all files in the install dir properly, so this fix should be ready to merge..?

**Comment by jonathansick** [comment]
Thanks @mssgill.

**Pull request merged**
